
export const databaseConstants = {
    FETCH_DATABASE_LIST: "FETCH_DATABASE_LIST",
    FETCH_TABLE_LIST: "FETCH_TABLE_LIST",
    FETCH_ATTRIBUTES: "FETCH_ATTRIBUTES",
    FETCH_DATA: "FETCH_DATA",
    SET_RED_TABLES: "SET_RED_TABLES",
    SET_GREEN_TABLES: "SET_GREEN_TABLES",
}